--
SELECT NAME
FROM CITY
WHERE POPULATION > 120000 && COUNTRYCODE = 'USA'

--
SELECT *
FROM CITY
WHERE ID = 1661

--
SELECT DISTINCT CITY
FROM STATION
WHERE ID % 2 = 0

--
SELECT (COUNT(CITY) - COUNT(DISTINCT CITY)) FROM STATION

--
SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP "^[aeiou](.)+"

--
SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP "^[^aeiou](.)+|(.)+[^aeiou]$"

--
SELECT Name
FROM STUDENTS
WHERE Marks > 75
ORDER BY SUBSTR(Name, LENGTH(Name)-2, LENGTH(Name)), ID

--
SELECT
    CASE
        WHEN A=B&&B=C THEN 'Equilateral'
        WHEN A+B<=C || B+C<=A || C+A<=B THEN 'Not A Triangle'
        WHEN A=B || B=C || C=A THEN 'Isosceles'
        ELSE 'Scalene'
    END
FROM TRIANGLES

